### ISSUE TITLE
Sorting by percentage yields the wrong results

### ISSUE THREAD

**Issue by ruphy** [italia/report-vaccini-anti-covid-19#1]
Regions with an integer percentage of vaccinations get incorrectly sorted before all others.

See screenshot for details, Sicily shouldn't be the first in the list:

![image](https://user-images.githubusercontent.com/2030/104379866-64057a00-552a-11eb-960c-cd181c1947a9.png)

**Comment by umberto-titola** [comment]
Thanks for reporting

**Comment by umberto-titola** [comment]
> Regions with an integer percentage of vaccinations get incorrectly sorted before all others.
> 
> See screenshot for details, Sicily shouldn't be the first in the list:
> 
> ![image](https://user-images.githubusercontent.com/2030/104379866-64057a00-552a-11eb-960c-cd181c1947a9.png)

thanks for reporting, the bug has been fixed
